- name: Cumulus configure
  shell: |
    cat >> /etc/network/interfaces << EOF
    auto swp{{ item.key }}
    iface swp{{ item.key }}
        address {{ item.value.key }}/{{ item.value.value | ipaddr('prefix') }}
        broadcast {{ item.value.value | ipaddr('broadcast') }}
    EOF
    ifreload -a
  with_dict: "{{ iPAddressDict }}"
  when: iPAddressDict is defined
- name: Routing VNFD
  shell: |
    ip rule add from {{ item.sourceAddr }} to {{ item.destAddr }} table 10
  with_items: "{{ Routing_rules }}"
  when: Routing_rules is defined and item.sourceAddr is defined and item.destAddr is defined 

- name: Routing VNFD
  shell: |
    ip rule add to {{ item.destAddr }} table 10
  with_items: "{{ Routing_rules }}"
  when: Routing_rules is defined and item.sourceAddr is not defined and item.destAddr is defined 
  
- name: Routing VNFD
  shell: |
    ip rule add from {{ item.sourceAddr }} table 10
  with_items: "{{ Routing_rules }}"
  when: Routing_rules is defined and item.sourceAddr is defined and item.destAddr is not defined 
  
- name: Routing VNFD
  shell: |
    ip route add {{ item.destCidr }} via {{ item.gateway }} dev {{ item.dev }} src {{ item.src }} table 10
  with_items: "{{ Routing_routes }}"
  when: Routing_routes is defined and item.src is defined
  
- name: Routing VNFD
  shell: |
    ip route add {{ item.destCidr }} via {{ item.gateway }} dev {{ item.dev }} table 10
  with_items: "{{ Routing_routes }}"
  when: Routing_routes is defined and item.src is not defined
